Update tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,11 +8,9 @@ on: [push, pull_request]
 
 jobs:
   test:
-    # --- Job Environment ---
     # Use the latest version of Ubuntu to run the job
     runs-on: ${{ matrix.os }}
 
-    # --- Test Matrix ---
     # Run the tests on all supported Python versions
     strategy:
       matrix:
@@ -20,18 +18,46 @@ jobs:
         os: [ubuntu-latest, windows-latest]
 
     steps:
-      # --- 1. Check out the repository code ---
       - name: Check out code
         uses: actions/checkout@v4
 
-      # --- 2. Set up the specific Python version from the matrix ---
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
 
-      # --- 3. Install dependencies ---
-      # This step installs your package along with its testing dependencies (pytest)
+      - name: Download Mold2 Executable
+        env:
+          GH_TOKEN: ${{ secrets.GH_PAT }}
+        shell: bash
+        run: |
+          RELEASE_TAG="assets"
+          ASSET_FILENAME="mold2_exec.zip"
+
+          echo "Fetching asset ID..."
+          asset_id=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
+            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG}" | \
+            jq '.assets[] | select(.name=="Mold2-Executable-File.zip") | .id')
+
+          if [ -z "$asset_id" ] || [ "$asset_id" == "null" ]; then
+            echo "::error::Could not find asset ID for 'Mold2-Executable-File.zip' in release '$RELEASE_TAG'."
+            exit 1
+          fi
+
+          echo "Downloading asset to the repository root..."
+          curl -L -o "$ASSET_FILENAME" \
+            -H "Accept: application/octet-stream" \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            "https://api.github.com/repos/${{ github.repository }}/releases/assets/${asset_id}"
+
+          if [ ! -f "$ASSET_FILENAME" ]; then
+            echo "::error::Failed to download the asset."
+            exit 1
+          fi
+          echo "Asset downloaded successfully."
+
+
+      # This step installs the package along with its testing dependencies (pytest)
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
